# Generated by Django 4.2.6 on 2023-10-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_amenity_deleted_at_alter_booking_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.ManyToManyField(blank=True, to="app.amenity"),
        ),
        migrations.DeleteModel(
            name="RoomAmenity",
        ),
    ]
