# Generated by Django 4.2.6 on 2023-10-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_booking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="restriction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
